### PR TITLE
Fix locale date formats

### LINKED ISSUE #1385: Date question type has invalid format

### PR DESCRIPTION
**Pull request by idelcano**
Closes #1385
The date tipe wasn't invalid, but we was saving and pushing the default locale format and this is incompatible with the server in some cases.

The value is now pushed and stored with the server format, but is displayed with the locale format in the views.

### CODE REVIEW

File: app/src/main/java/org/eyeseetea/malariacare/domain/entity/DateQuestion.java [hunk 1]
```diff
@@ -0,0 +1,120 @@
...
+
+import org.eyeseetea.malariacare.database.iomodules.dhis.importer.models.EventExtended;
+import org.eyeseetea.malariacare.database.utils.PreferencesState;
+import org.eyeseetea.malariacare.domain.exception.DateFormatException;
+
+import java.text.ParseException;
+import java.util.Date;
+import java.util.Locale;
+
+public class DateQuestion {
```
Comment (xurxodev) [inline app/src/main/java/org/eyeseetea/malariacare/domain/entity/DateQuestion.java]: @idelcano this is not a entity, It looks more like a utils class with all methods static that we have to try to avoid. A entities are domain concepts for example value, survey, question but not exists yet. In this case the responsability to convert date formats is of adapters, remember that adapters translate information from and to domain. We still do not have very defined domain and adapters according to clean architecture but conversions with current state can be done from ConvertToSDKVisitor, ConvertFromSDKVisitor and from activity, fragment or adapter that render the date on the screen.

Comment (idelcano) [inline app/src/main/java/org/eyeseetea/malariacare/domain/entity/DateQuestion.java]: @xurxodev understood, fixed.
Thanks for the explanation.
I tried to do something similar to the Positive or Zero class in pictureapp, but it is finally different
